name: Test APITesting Project

on:
  pull_request_target:
    types: [opened, reopened]
    branches: ["main", "master"]

jobs:
  test-project:
    uses: UdaraWickramarathne/ap-actions/blob/main/.github/workflows/ap-java.yml@main
    with:
        pr_head_sha: ${{ github.event.pull_request.head.sha }}
